version: '3'
services:
  user-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/enigma-server
    ports:
      - 8080:8080
    environment:
      - MY_LOG_LEVEL=info
      - MY_LOG_STYLE=Always
    command: "cargo watch -x run"
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
