POST http://localhost:8000/experiment
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjEwMDAwMDAwMDAwMDAsInVzZXIiOnsiaWQiOiJ1c2VyXzAxIiwidXNlcm5hbWUiOiJ0ZXN0YWRtaW4iLCJhbGlhcyI6InRlc3QgYWRtaW4iLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifX0.VH_aV-PK80sqdZzwh4Ln4dSQwRZHzwXlAxhVXgxk3Xo

{
    "title": "Mu test experiment",
    "description": "Mu test experiment",
    "active_interval": ["2007-04-05T14:30:30Z", "2007-04-05T14:30:30Z"],
    "variations": [
        { 
            "group": "A",
            "description": "Treatment A",
            "indicator": "treatment-a",
            "weight": 1,
            "values": {
                "var1": "A",
                "var2": 1
            }
        },
        { 
            "group": "B",
            "description": "Treatment B",
            "indicator": "treatment-b",
            "weight": 1,
            "values": {
                "var1": "B",
                "var2": 2
            }
        },
        { 
            "group": "Control",
            "description": "Control group",
            "indicator": "control",
            "weight": 1,
            "values": {
                "var1": "",
                "var2": 0
            }
        }
    ],
    "group_assign": {
        "strategy": "random",
        "persistent": "key_contextual"
    }
}

###

GET http://localhost:8000/experiment/6209676d09416bc0cfbda31a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjEwMDAwMDAwMDAwMDAsInVzZXIiOnsiaWQiOiJ1c2VyXzAxIiwidXNlcm5hbWUiOiJ0ZXN0YWRtaW4iLCJhbGlhcyI6InRlc3QgYWRtaW4iLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifX0.VH_aV-PK80sqdZzwh4Ln4dSQwRZHzwXlAxhVXgxk3Xo

