@hostname = localhost:8000
@jwt_token = eyJhbGciOiJIUzI1NiJ9.ewogICAgInN1YiI6ICIxMjM0NTY3ODkwIiwKICAgICJuYW1lIjogImFkbWluMDEiLAogICAgImlhdCI6IDE1MTYyMzkwMjIsCiAgICAiZXhwIjogMTAwMDAwMDAwMDAwMCwKICAgICJ1c2VyIjogewogICAgICAgICJpZCI6ICJ1c2VyXzAxIiwKICAgICAgICAidXNlcm5hbWUiOiAidGVzdGFkbWluIiwKICAgICAgICAiYWxpYXMiOiAidGVzdCBhZG1pbiIsCiAgICAgICAgImVtYWlsIjogInRlc3RAZXhhbXBsZS5jb20iLAogICAgICAgICJjaGFubmVsX2lkIjogIjEwMDAwMDAxIgogICAgfQp9.uX0shLY0SmaEv_PBuLkTo6Aw2tK4N29Vq7fmzlPPju0
###

GET http://{{hostname}}/hey

###

POST http://{{hostname}}/experiment
Content-Type: application/json
Authorization: bearer {{jwt_token}}

{
    "name": "Hello world 2",
    "description": "Mu test experiment v2",
    "active_interval": ["2007-04-05T14:30:30Z", "2007-04-05T14:30:30Z"],
    "variances": [
        { 
            "group_name": "A",
            "description": "Treatment A",
            "indicator": "treatment-a",
            "weight": 1,
            "values": {
                "var1": "A",
                "var2": 1
            }
        },
        { 
            "group_name": "B",
            "description": "Treatment B",
            "indicator": "treatment-b",
            "weight": 1,
            "values": {
                "var1": "B",
                "var2": 2
            }
        },
        { 
            "group_name": "Control",
            "description": "Control group",
            "indicator": "control",
            "weight": 1,
            "values": {
                "var1": "",
                "var2": 0
            }
        }
    ],
    "classing": {
        "strategy": "random",
        "persistent_mode": "key_contextual"
    }
}

###

GET http://{{hostname}}/experiments
Content-Type: application/json
Authorization: bearer {{jwt_token}}

###

GET http://{{hostname}}/experiment/62bf0ef51ff25598aafa3e66
Content-Type: application/json
Authorization: bearer {{jwt_token}}
