POST http://localhost:8000/experiment
Content-Type: application/json

{
    "title": "Mu test experiment",
    "description": "Mu test experiment",
    "active_interval_from": "2007-04-05T14:30:30",
    "active_interval_to": "2007-04-05T14:30:30"
}